### ISSUE TITLE
How to install 'pyEDS' module

### ISSUE THREAD

**Issue by PhysXu** [RhettZhou/pyEDS#2]
Hi, thanks for sharing the codes!
I followed the instruction for the installation, but have a error when running the jupyter file:
![image](https://user-images.githubusercontent.com/35793078/197914980-33b3c2da-49ed-45e2-ac44-bffd81c17b29.png)

......
I noted that, in the instruction for the installation, it has no codes for installing the module of pyEDS.
How to solve this?
Any reply will be appreciated!

**Comment by RhettZhou** [comment]
Hello, [PhysXu](https://github.com/PhysXu), many thanks for your interest!! 

To solve this problem, you can simply put your Jupyter file in the same folder as "pyEDS". The folder "pyEDS" is the one you downloaded "..\python\". 

I hope that this could work for you. 

![image](https://user-images.githubusercontent.com/51905661/197943755-c6a0c9f0-1298-45d9-aa94-1b2c2843bb80.png)

Note: We did not compile "pyEDS" as a single module, but used the files in the "pyEDS" folder.

**Comment by PhysXu** [comment]
> Hello, [PhysXu](https://github.com/PhysXu), many thanks for your interest!!
> 
> To solve this problem, you can simply put your Jupyter file in the same folder as "pyEDS". The folder "pyEDS" is the one you downloaded "..\python".
> 
> I hope that this could work for you.
> 
> ![image](https://user-images.githubusercontent.com/51905661/197943755-c6a0c9f0-1298-45d9-aa94-1b2c2843bb80.png)
> 
> Note: We did not compile "pyEDS" as a single module, but used the files in the "pyEDS" folder.

Thanks!
The error message disappeared.
